import {
  DefaultValues,
  toPlanetoidPresetSettings,
} from '../../lib/components/Threlte/Planetoid/PlanetoidSettings'
import type { PlanetoidPreset } from './types'

export const iceworldPreset: PlanetoidPreset = {
  id: 'builtin-iceworld',
  name: 'Iceworld',
  settings: toPlanetoidPresetSettings({
    ...DefaultValues,
    palette: 'icy',
    surfaceTint: '#87b7de',
    colorScale: 1.2,
    tintShadowFloor: 0,
    swirliness: 0.5,
    dustCloudCoverage: 0.75,
    dustCloudStyle: 'worley',
    dustCloudWeights: { ...DefaultValues.dustCloudWeights, wisps: 0, worley: 1 },
    dustCloudPalette: 'silicate',
    dustCloudOpacity: 0.75,
    dustCloudElevation: 0.01,
    dustCloudFrequency: 0.8,
    dustCloudSwirliness: 2,
    dustCloudCoriolis: 2,
    dustCloudNormalStrength: 0.15,
    atmospherePalette: 'glacial',
    atmosphereIntensity: 2,
    atmosphereThickness: 0.12,
    atmosphereDropoff: 4,
    atmosphereTerminatorWrap: 0.3,
    craterCount: 50,
    craterScale: 1,
    craterStrength: 2,
    craterSharpness: 3.5,
    craterColorStrength: 0.45,
    volcanoCount: 50,
    volcanoScale: 0.35,
    volcanoStrength: 3,
    volcanoColorStrength: 1,
    ridgeColorWeight: 0.65,
    riftColorWeight: 0.25,
    enableCraters: true,
    enableVolcanoes: false,
    enableRidges: false,
    enableRifts: false,
    enableDustClouds: true,
    enableAtmosphere: true,
    ridgeStrength: 0.2,
    ridgeFrequency: 8,
    ridgeSharpness: 2,
    riftStrength: 0.7,
    riftFrequency: 3,
    riftWidth: 0.2,
    riftSharpness: 4,
    ridgesRiftsBlend: 0.5,
    largeScale: 0,
    mediumScale: 0,
    smallScale: 0,
    mediumFrequency: 1,
    smallFrequency: 4,
    triangleDetail: 15,
    normalStrength: 0.5,
    roughness: 0.9,
    metalness: 0.5,
  }),
}
