import {
  DefaultValues,
  toPlanetoidPresetSettings,
} from '../../lib/components/Threlte/Planetoid/PlanetoidSettings'
import type { PlanetoidPreset } from './types'

export const ioPreset: PlanetoidPreset = {
  id: 'builtin-io',
  name: 'Io',
  settings: toPlanetoidPresetSettings({
    ...DefaultValues,
    palette: 'io',
    surfaceTint: '#87b7de',
    colorScale: 1.3,
    tintShadowFloor: 0,
    swirliness: 0.2,
    dustCloudCoverage: 0.65,
    dustCloudStyle: 'worley',
    dustCloudPalette: 'sulfur',
    dustCloudOpacity: 0.5,
    dustCloudElevation: 0.01,
    dustCloudFrequency: 0.8,
    dustCloudSwirliness: 2,
    dustCloudCoriolis: 2,
    dustCloudNormalStrength: 0.15,
    atmospherePalette: 'titan',
    atmosphereIntensity: 3,
    atmosphereThickness: 0.08,
    atmosphereDropoff: 4,
    atmosphereTerminatorWrap: 0.5,
    craterCount: 25,
    craterScale: 1.2,
    craterStrength: 3,
    craterSharpness: 3.5,
    craterColorStrength: 0.45,
    volcanoCount: 25,
    volcanoScale: 0.6,
    volcanoStrength: 3,
    volcanoColorStrength: 1,
    ridgeColorWeight: 0.5,
    riftColorWeight: 0.25,
    enableCraters: true,
    enableVolcanoes: true,
    enableRidges: true,
    enableRifts: true,
    enableDustClouds: true,
    enableAtmosphere: true,
    ridgeStrength: 0.8,
    ridgeFrequency: 4,
    ridgeSharpness: 4,
    riftStrength: 0.5,
    riftFrequency: 3,
    riftWidth: 0.05,
    riftSharpness: 5,
    ridgesRiftsBlend: 1,
    largeScale: 0,
    mediumScale: 0,
    smallScale: 0,
    mediumFrequency: 1,
    smallFrequency: 4,
    triangleDetail: 15,
    normalStrength: 0.5,
    roughness: 0.9,
    metalness: 0.5,
  }),
}
