import {
  DefaultValues,
  toPlanetoidPresetSettings,
} from '../../lib/components/Threlte/Planetoid/PlanetoidSettings'
import type { PlanetoidPreset } from './types'

export const ioPreset: PlanetoidPreset = {
  id: 'builtin-io',
  name: 'Io',
  settings: toPlanetoidPresetSettings({
    ...DefaultValues,
    palette: 'io',
    surfaceTint: '#c4b9a2',
    colorScale: 1,
    tintShadowFloor: 0,
    swirliness: 0.2,
    craterCount: 20,
    craterStrength: 2,
    craterColorStrength: 0.45,
    volcanoCount: 60,
    volcanoScale: 2.2,
    volcanoStrength: 1.65,
    volcanoColorStrength: 2.2,
    ridgeColorWeight: 0.65,
    riftColorWeight: 0.25,
    enableCraters: false,
    enableRidges: false,
    enableRifts: true,
    enableVolcanoes: true,
    ridgeStrength: 0.8,
    ridgeFrequency: 8,
    ridgeSharpness: 2,
    riftStrength: 0.4,
    riftFrequency: 1.5,
    riftWidth: 0.05,
    riftSharpness: 2,
    ridgesRiftsBlend: 0.5,
    largeScale: 0,
    mediumScale: 0,
    smallScale: 0,
    triangleDetail: 15,
    normalStrength: 0.5,
    roughness: 0.8,
    metalness: 0.5,
  }),
}
