import {
  DefaultValues,
  toPlanetoidPresetSettings,
} from '../../lib/components/Threlte/Planetoid/PlanetoidSettings'
import type { PlanetoidPreset } from './types'

export const marsPreset: PlanetoidPreset = {
  id: 'builtin-mars',
  name: 'Mars',
  settings: toPlanetoidPresetSettings({
    ...DefaultValues,
    palette: 'martian',
    surfaceTint: '#87b7de',
    colorScale: 1.1,
    tintShadowFloor: 0,
    swirliness: 0.5,
    dustCloudCoverage: 0.7,
    dustCloudStyle: 'worley',
    dustCloudPalette: 'silicate',
    dustCloudOpacity: 0.3,
    dustCloudElevation: 0.01,
    dustCloudFrequency: 1,
    dustCloudSwirliness: 2,
    dustCloudCoriolis: 2,
    dustCloudNormalStrength: 0.15,
    atmospherePalette: 'martian',
    atmosphereIntensity: 2.45,
    atmosphereThickness: 0.12,
    atmosphereDropoff: 4,
    atmosphereTerminatorWrap: 0.5,
    craterCount: 25,
    craterScale: 1.2,
    craterStrength: 3,
    craterSharpness: 3.5,
    craterColorStrength: 0.45,
    volcanoCount: 50,
    volcanoScale: 0.35,
    volcanoStrength: 3,
    volcanoColorStrength: 1,
    ridgeColorWeight: 1,
    riftColorWeight: 0.25,
    enableCraters: true,
    enableVolcanoes: false,
    enableRidges: true,
    enableRifts: true,
    enableDustClouds: true,
    enableAtmosphere: true,
    ridgeStrength: 0.4,
    ridgeFrequency: 8,
    ridgeSharpness: 4,
    riftStrength: 0.7,
    riftFrequency: 3,
    riftWidth: 0.2,
    riftSharpness: 4,
    ridgesRiftsBlend: 0.5,
    largeScale: 0,
    mediumScale: 0,
    smallScale: 0,
    mediumFrequency: 1,
    smallFrequency: 4,
    triangleDetail: 15,
    normalStrength: 0.5,
    roughness: 0.9,
    metalness: 0.5,
  }),
}
