import {
  DefaultValues,
  toPlanetoidPresetSettings,
} from '../../lib/components/Threlte/Planetoid/PlanetoidSettings'
import type { PlanetoidPreset } from './types'

export const marsPreset: PlanetoidPreset = {
  id: 'builtin-mars',
  name: 'Mars',
  settings: toPlanetoidPresetSettings({
    ...DefaultValues,
    palette: 'martian',
    surfaceTint: '#c4b9a2',
    colorScale: 1,
    tintShadowFloor: 0,
    swirliness: 0.3,
    craterCount: 20,
    craterStrength: 2,
    craterColorStrength: 0.45,
    volcanoCount: 50,
    volcanoScale: 0.35,
    volcanoStrength: 3,
    volcanoColorStrength: 1,
    ridgeColorWeight: 0.65,
    riftColorWeight: 0.25,
    enableCraters: true,
    enableRidges: false,
    enableRifts: true,
    enableVolcanoes: false,
    ridgeStrength: 0.8,
    ridgeFrequency: 8,
    ridgeSharpness: 2,
    riftStrength: 0.4,
    riftFrequency: 1.5,
    riftWidth: 0.05,
    riftSharpness: 2,
    ridgesRiftsBlend: 0.5,
    largeScale: 0,
    mediumScale: 0,
    smallScale: 0,
    triangleDetail: 15,
    normalStrength: 1,
    roughness: 0.8,
    metalness: 0.5,
  }),
}
