import {
  DefaultValues,
  toPlanetoidPresetSettings,
} from '../../lib/components/Threlte/Planetoid/PlanetoidSettings'
import type { PlanetoidPreset } from './types'

export const marsWinterPreset: PlanetoidPreset = {
  id: 'builtin-mars-winter',
  name: 'Martian Winter',
  settings: toPlanetoidPresetSettings({
    ...DefaultValues,
    palette: 'martian',
    surfaceTint: '#87b7de',
    colorScale: 1.1,
    tintShadowFloor: 0,
    swirliness: 0.2,
    normalStrength: 0.5,
    roughness: 0.9,
    metalness: 0.5,
    enableIceCaps: true,
    iceCapPalette: 'glacial',
    iceCapColor: '#ffffff',
    iceCapCoverage: 0.13,
    iceCapEdgeNoise: 0.25,
    snowExtent: 0.11,
    snowCoverage: 0.7,
    enableDustClouds: true,
    dustCloudPalette: 'ferric',
    dustCloudWeights: {
      wisps: 0,
      worley: 1,
      cumulonimbus: 0,
      storm: 0,
      stormWorley: 0,
    },
    dustCloudCoverage: 0.7,
    dustCloudOpacity: 0.3,
    dustCloudElevation: 0.01,
    dustCloudFrequency: 1,
    dustCloudSwirliness: 2,
    dustCloudCoriolis: 2,
    dustCloudNormalStrength: 0.15,
    enableAtmosphere: true,
    atmospherePalette: 'glacial',
    atmosphereIntensity: 2,
    atmosphereThickness: 0.12,
    atmosphereDropoff: 4,
    atmosphereTerminatorWrap: 0.5,
    enableCraters: true,
    craterCount: 40,
    craterScale: 1.2,
    craterStrength: 3,
    craterSharpness: 3.5,
    craterColorStrength: 0.45,
    enableVolcanoes: true,
    volcanoCount: 40,
    volcanoScale: 0.35,
    volcanoStrength: 3,
    volcanoColorStrength: 1,
    enableRidges: true,
    ridgeStrength: 0.4,
    ridgeFrequency: 4,
    ridgeSharpness: 4,
    ridgeColorWeight: 1,
    ridgesRiftsBlend: 0.5,
    enableRifts: true,
    riftStrength: 0.5,
    riftFrequency: 3,
    riftWidth: 0.2,
    riftSharpness: 4,
    riftColorWeight: 0.1,
    largeScale: 0,
    mediumScale: 0,
    smallScale: 0,
    mediumFrequency: 1,
    smallFrequency: 4,
  }),
}
