import {
  DefaultValues,
  toPlanetoidPresetSettings,
} from '../../lib/components/Threlte/Objects/PlanetoidSettings'
import type { PlanetoidPreset } from './types'

export const mineralAsteroidPreset: PlanetoidPreset = {
  id: 'builtin-mineral-asteroid',
  name: 'Mineral asteroid',
  settings: toPlanetoidPresetSettings({
    ...DefaultValues,
    palette: 'mineralVeins',
    surfaceTint: '#cf9b7d',
    colorScale: 0.92,
    tintShadowFloor: 0.18,
    swirliness: 0.85,
    craterCount: 20,
    craterStrength: 6,
    craterColorStrength: 1.9,
    volcanoCount: 24,
    volcanoScale: 2,
    volcanoStrength: 2.2,
    volcanoColorStrength: 1.7,
    ridgeColorWeight: 2.35,
    riftColorWeight: 0.75,
    craterRayStrength: 0,
    craterRayVisibility: 0,
    craterRayDensity: 0.3,
    craterRaySharpness: 0.5,
    craterRayLengthPower: 1,
    enableCraters: true,
    enableVolcanoes: false,
    enableRidges: true,
    enableRifts: true,
    ridgeStrength: 0.4,
    ridgeFrequency: 2.5,
    ridgeSharpness: 4,
    riftStrength: 1,
    riftFrequency: 2,
    riftWidth: 0.24,
    riftSharpness: 1.75,
    ridgesRiftsBlend: 0.5,
    largeScale: 0.4,
    mediumScale: 1.2,
    smallScale: 0.03,
    mediumFrequency: 0.5,
    smallFrequency: 4.3,
    triangleDetail: 40,
    normalStrength: 2,
    roughness: 0.75,
    metalness: 0.4,
  }),
}
