import {
  DefaultValues,
  toPlanetoidPresetSettings,
} from '../../lib/components/Threlte/Objects/PlanetoidSettings'
import type { PlanetoidPreset } from './types'

export const potatoPreset: PlanetoidPreset = {
  id: 'builtin-potato',
  name: 'Potato',
  settings: toPlanetoidPresetSettings({
    ...DefaultValues,
    palette: 'sulfuricGlass',
    surfaceTint: '#d8ecff',
    colorScale: 1,
    tintShadowFloor: 0.32,
    swirliness: 0.3,
    craterCount: 20,
    craterStrength: 0.5,
    craterColorStrength: 2.05,
    volcanoCount: 12,
    volcanoScale: 2,
    volcanoStrength: 2,
    volcanoColorStrength: 1.2,
    ridgeColorWeight: 0.1,
    riftColorWeight: 0.25,
    enableCraters: true,
    enableRidges: false,
    enableRifts: false,
    enableVolcanoes: false,
    ridgeStrength: 2,
    ridgeFrequency: 2.5,
    ridgeSharpness: 2.5,
    riftStrength: 0.75,
    riftFrequency: 1.5,
    riftWidth: 0.05,
    riftSharpness: 2,
    ridgesRiftsBlend: 0.5,
    largeScale: 0.9,
    mediumScale: 0,
    smallScale: 0,
    triangleDetail: 15,
    normalStrength: 1,
    roughness: 0.8,
    metalness: 0.5,
  }),
}
