import { DefaultValues, type StarSettings } from '../../lib/components/Threlte/Star/StarSettings'

// Shared look for the built-in stars; presets differ only by palette.
export const BaseStarSettings: StarSettings = {
  ...DefaultValues,
  brightness: 1,
  saturation: 1.5,
  contrast: 1,
  limbBrightness: 0.5,
  haloIntensity: 1.5,
  haloFalloff: 8,
  haloSize: 1.25,
  haloTurbulence: 1,
  plasmaIntensity: 16,
  plasmaSurfaceIntensity: 3,
  plasmaExtent: 1,
  plasmaTurbulence: 2,
  plasmaSharpness: 1,
  plasmaTextureScale: 4,
  textureScale: 1,
  bandContrast: 1,
  bandSwirl: 1,
  granularity: 4,
  turbulence: 8,
  convection: 0.8,
  sunspotCount: 12,
  sunspotScale: 0.6,
  sunspotPower: 4,
  sunspotJaggedness: 0.3,
  sunspotNeighbours: 5,
  penumbraScale: 1.2,
  sunspotDarkness: 0.5,
  colorTextureSize: 2048,
}
