import { DefaultPlanetoidSettings } from '../../lib/components/Threlte/Objects/PlanetoidSettings'
import type { PlanetoidPreset } from './types'

export const iceworldPreset: PlanetoidPreset = {
  id: 'builtin-iceworld',
  name: 'Iceworld',
  settings: {
    ...DefaultPlanetoidSettings,
    palette: 'icy',
    surfaceTint: '#d8ecff',
    colorScale: 0.82,
    tintShadowFloor: 0.32,
    swirliness: 0.15,
    craterCount: 44,
    craterStrength: 6.8,
    craterColorStrength: 1.4,
    volcanoCount: 12,
    volcanoScale: 2,
    volcanoStrength: 2,
    volcanoColorStrength: 1.2,
    ridgeColorWeight: 0.1,
    riftColorWeight: 0.25,
    craterRayStrength: 2.6,
    craterRayVisibility: 1,
    craterRayDensity: 1,
    craterRaySharpness: 1,
    craterRayLengthPower: 2.8,
    enableCraters: true,
    enableRidges: false,
    enableRifts: false,
    enableVolcanoes: false,
    ridgeStrength: 2,
    ridgeScale: 2.5,
    ridgeSharpness: 2.5,
    riftStrength: 0.75,
    riftScale: 1.5,
    riftWidth: 0.05,
    riftSharpness: 2,
    ridgesRiftsBlend: 0.5,
    bumpTextureSize: 1024,
    colorTextureSize: 1024,
    seed: 1,
    largeScale: 0.35,
    mediumScale: 0.2,
    smallScale: 0.15,
    triangleDetail: 15,
    bumpScale: 2.3,
    roughness: 0.2,
    metalness: 0.6,
  },
}
