import { DefaultPlanetoidSettings } from '../../lib/components/Threlte/Objects/PlanetoidSettings'
import type { PlanetoidPreset } from './types'

export const marsPreset: PlanetoidPreset = {
  id: 'builtin-mars',
  name: 'Mars',
  settings: {
    ...DefaultPlanetoidSettings,
    palette: 'martian',
    surfaceTint: '#c4b9a2',
    colorScale: 1,
    tintShadowFloor: 0,
    swirliness: 0.3,
    craterCount: 20,
    craterStrength: 2,
    craterColorStrength: 1,
    volcanoCount: 50,
    volcanoScale: 0.35,
    volcanoStrength: 3,
    volcanoColorStrength: 1,
    ridgeColorWeight: 0.65,
    riftColorWeight: 0.25,
    craterRayStrength: 5,
    craterRayVisibility: 1,
    craterRayDensity: 1,
    craterRaySharpness: 4,
    craterRayLengthPower: 2.8,
    enableCraters: true,
    enableRidges: false,
    enableRifts: true,
    enableVolcanoes: false,
    ridgeStrength: 0.8,
    ridgeScale: 8,
    ridgeSharpness: 2,
    riftStrength: 0.4,
    riftScale: 1.5,
    riftWidth: 0.05,
    riftSharpness: 2,
    ridgesRiftsBlend: 0.5,
    bumpTextureSize: 1024,
    colorTextureSize: 1024,
    seed: 1,
    largeScale: 0,
    mediumScale: 0,
    smallScale: 0,
    triangleDetail: 15,
    bumpScale: 1,
    roughness: 0.8,
    metalness: 0.5,
  },
}
