import type { PlanetoidPreset } from './types'

export const marsPreset: PlanetoidPreset = {
  id: 'builtin-mars',
  name: 'Mars',
  settings: {
    palette: 'martian',
    surfaceTint: '#ac8d77',
    colorScale: 1,
    tintShadowFloor: 0.32,
    swirliness: 0.3,
    craterCount: 20,
    craterStrength: 0.5,
    craterColorStrength: 2.05,
    volcanoCount: 12,
    volcanoScale: 2,
    volcanoStrength: 2,
    volcanoColorStrength: 1.2,
    ridgeColorWeight: 0.2,
    riftColorWeight: 0.25,
    craterRayStrength: 0,
    craterRayVisibility: 0,
    craterRayDensity: 1,
    craterRaySharpness: 1,
    craterRayLengthPower: 2.8,
    enableCraters: false,
    enableRidges: false,
    enableRifts: false,
    enableVolcanoes: false,
    ridgeStrength: 2,
    ridgeScale: 1.4,
    ridgeSharpness: 0.5,
    riftStrength: 0.45,
    riftScale: 1.5,
    riftWidth: 0.05,
    riftSharpness: 2,
    ridgesRiftsBlend: 1,
    bumpTextureSize: 1024,
    colorTextureSize: 1024,
    largeScale: 0,
    mediumScale: 0,
    smallScale: 0,
    triangleDetail: 20,
    bumpScale: 1,
    roughness: 0.8,
    metalness: 0.5,
    autoRotate: false,
    showDebugMeshes: false,
  },
}

