import type { PlanetoidPreset } from './types'

export const potatoPreset: PlanetoidPreset = {
  id: 'builtin-potato',
  name: 'Potato',
  settings: {
    palette: 'sulfuricGlass',
    surfaceTint: '#d8ecff',
    colorScale: 1,
    tintShadowFloor: 0.32,
    swirliness: 0.3,
    craterCount: 20,
    craterStrength: 0.5,
    craterColorStrength: 2.05,
    volcanoCount: 12,
    volcanoScale: 2,
    volcanoStrength: 2,
    volcanoColorStrength: 1.2,
    ridgeColorWeight: 0.1,
    riftColorWeight: 0.25,
    craterRayStrength: 0,
    craterRayVisibility: 0,
    craterRayDensity: 1,
    craterRaySharpness: 1,
    craterRayLengthPower: 2.8,
    enableRidges: false,
    enableRifts: false,
    enableVolcanoes: false,
    ridgeStrength: 2,
    ridgeScale: 2.5,
    ridgeSharpness: 2.5,
    riftStrength: 0.75,
    riftScale: 1.5,
    riftWidth: 0.05,
    riftSharpness: 2,
    ridgesRiftsBlend: 0.5,
    bumpTextureSize: 1024,
    colorTextureSize: 1024,
    seed: 5,
    largeScale: 0.9,
    mediumScale: 0,
    smallScale: 0,
    triangleDetail: 15,
    bumpScale: 2,
    roughness: 0.8,
    metalness: 0.5,
    autoRotate: false,
    showDebugMeshes: false,
  },
}

